@echo off

ping -n 2 localhost >nul
echo  Setings Verison: 1.0
ping -n 2 localhost >nul
echo  Date Made: 10/18/2022
ping -n 4 localhost >nul
echo=
ping -n 2 localhost >nul
echo  you Can Get more of My cool Programs
echo  Frum My youTube channol
ping -n 3 localhost >nul
echo=
echo  Here is The Link to My youTybe...
echo  https://www.youtube.com/channel/UC4Vd3tkFIKOqCablN2sJlhQ
ping -n 3 localhost >nul


"%~DP0%\data\password.ahk"

ping -n 3 localhost >nul
echo=
echo launching The setings Menu...
ping -n 2 localhost >nul

ping -n 3 localhost >nul
"%~DP0%\data\Setings.ahk"
ping -n 3 localhost >nul

echo=
"%~DP0%\data\close.ahk"
ping -n 2 localhost >nul


