; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 105

Gui -MaximizeBox
Gui Add, Edit, x88 y16 w120 h21
Gui Add, Text, x24 y0 w232 h15 +0x200, enter the password to get access to the settings
Gui Add, Link, x8 y32 w80 h15, <a href="https://www.youtube.com/channel/UC4Vd3tkFIKOqCablN2sJlhQ">My youTube</a>
Gui Add, Button, x240 y24 w38 h23, &OK

Gui Show, w288 h51, password 
Return

GuiEscape:
GuiClose:
    ExitApp
