; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 317

Gui -MaximizeBox
Gui Add, Tab3, x-8 y0 w225 h388, Window/Program | Date And Time
Gui Tab, 1
Gui Add, Picture, x24 y24 w176 h39, C:\Users\sire_\Desktop\Windows crash v4.0\data\Icons\Windows 10 Logo.png
Gui Add, Button, x168 y352 w45 h23, close
Gui Add, Button, x120 y352 w45 h23, Save
Gui Add, CheckBox, x8 y80 w81 h17, always on top
Gui Add, Link, x8 y368 w79 h13, <a href="https://www.youtube.com/channel/UC4Vd3tkFIKOqCablN2sJlhQ">My youTube</a>
Gui Add, Slider, x0 y120 w128 h15, 15
Gui Add, Text, x8 y104 w23 h18 +0x200, Size
Gui Add, Text, x8 y136 w9 h18 +0x200, 0
Gui Add, Text, x40 y136 w16 h18 +0x200, 10
Gui Add, Text, x24 y136 w9 h18 +0x200, 5
Gui Add, Text, x64 y136 w40 h18 +0x200, 15
Gui Add, Text, x88 y136 w16 h18 +0x200, 20
Gui Add, Text, x112 y136 w16 h18 +0x200, 25
Gui Add, Edit, x8 y184 w120 h21
Gui Add, Text, x8 y162 w74 h17 +0x200, Set a Passeord
Gui Add, Button, x136 y184 w36 h23, Set
Gui Add, Hotkey, x8 y232 w120 h21
Gui Add, Text, x8 y208 w47 h18 +0x200, Run Keys
Gui Tab, 2
Gui Add, Button, x168 y352 w45 h23, close
Gui Add, Button, x120 y352 w45 h23, Save
Gui Add, Picture, x24 y24 w176 h39, C:\Users\sire_\Desktop\Windows crash v4.0\data\Icons\Windows 10 Logo.png
Gui Add, DateTime, x8 y88 w100 h24
Gui Add, Text, x8 y72 w68 h16 +0x200, Set The Time
Gui Add, Link, x8 y368 w95 h15, <a href="https://autohotkey.com">Download autoGUI</a>
Gui Add, Text, x8 y120 w120 h16 +0x200, Time out Timer
Gui Add, Slider, x0 y136 w120 h32, 50
Gui Tab

Gui Show, x785 y194 w225 h387, Setings
Return

GuiSize:
    If (A_EventInfo == 1) {
        Return
    }

Return

GuiEscape:
GuiClose:
    ExitApp
